### ISSUE TITLE
It should work on any platform

### ISSUE THREAD

**Issue by MrRichBOB** [mike406/Simple-TTR-Launcher#1]
Just as a general statement, if it is written in python, it should work on any operating system so long as that OS has TTR installed. I could be wrong--I am working on installing getting the "official" TTR launcher to work in Linux at the moment. Yours seems to work perfectly, aside from the fact that I cannot test its launching feature as I cannot install the game on Linux because the "official" launcher is official garbage.

**Comment by mike406** [comment]
Hi there! It might run on Linux but lines 315 and 316 will need to be modified to work with the Linux TTR binary. Also I never tested if the Linux version uses those same environment variables, I got those from TTR’s login API. At some point I want to revisit it and formally test it on Linux and make it OS agnostic. As well as add support for patching the phase files. Appreciate you taking the time for writing!
