### ISSUE TITLE
"Could not find Toontown Rewritten" but the directory is set correctly

### ISSUE THREAD

**Issue by Sauromayne** [mike406/Simple-TTR-Launcher#2]
Hello Mike,

Love this project and hoping you can help me out. I see that you have updated the launch_ttr.py file recently to support 64bit. I also saw the last release for the project was in 2018 so I believe I am using an old version and that is why I am experiencing the issue.

I tried to build an exe file with PyInstaller but it just crashes. I also have tried to run the .py file through a command prompt but get a traceback on line 19 that says "ModuleNotFoundError: No module named 'requests' "
![image_2022-03-14_192129](https://user-images.githubusercontent.com/20719891/158293094-9f4453ad-5480-4fc5-afdd-4677181cd78b.png)

Maybe I have it all wrong and you don't need to release a new exe but please let me know if there is any way to get it working for me. I have some Python experience but I wasn't able to figure out how to get a working build on my PC with the updated py file.

My path for TTR is: 
C:\Program Files (x86)\Toontown Rewritten

And I will attach a picture of my JSON file:
![image_2022-03-14_192004](https://user-images.githubusercontent.com/20719891/158292940-f24b909a-52f6-4f52-b377-91dd3c081cf8.png)

I don't think I am doing anything wrong here, but whenever I try to play with the existing exe I get the error "Could not find Toontown Rewritten. Restart launcher and set your TTR directory at the menu."

![image_2022-03-14_191753](https://user-images.githubusercontent.com/20719891/158292696-fb7acb17-5c08-40a2-8721-5a417dddf444.png)

Thank you for taking a look!!

**Comment by mike406** [comment]
Hi there! Thanks for being interested in my project. To run the .py directly you’ll need to “pip install requests” to add that package to your computer. If it still gives you troubles I will make a new exe later today.

Source package: https://docs.python-requests.org/en/latest/user/install/#install

**Comment by Sauromayne** [comment]
> Hi there! Thanks for being interested in my project. To run the .py directly you’ll need to “pip install requests” to add that package to your computer. If it still gives you troubles I will make a new exe later today.
> 
> Source package: https://docs.python-requests.org/en/latest/user/install/#install

Hey there! Thanks for the quick response all is working fine after I ran "pip install requests". I am trying to use your simple launcher to make logins quicker when playing via Steam Link. Therefore, I need an exe to add to steam to tell it where the game starts.

I did work around this by creating a batch file, then converting the batch to an exe which works fine, but seems sloppy. How would you build an exe from the Python file? I am mainly just curious why it wasn't working when I tried to build it using pyinstaller. I am working to become a software developer someday so knowing how to do these things would be beneficial. If it is a lot to explain then no worries, I will figure it out eventually and at least I have the simple launcher working now!

**Comment by mike406** [comment]
I use the --onefile flag with pyinstaller so that it bundles everything into one .exe. Note that this often causes Windows Defender to freak out sometimes. There’s nothing malicious but sometimes the nature of the portable .exe makes Windows Defender nervous as a lot of Python written malware use pyinstaller. So you’ll probably be fighting with your antivirus exceptions for a bit if that happens, but once you have your exe you should be able to link it to Steam.

If I remember tonight, I’ll build a new exe and add to the releases. My next step with this project will be integrating patching of the game’s files rather than needing to run the official launcher to get game updates.

**Comment by Sauromayne** [comment]
> I use the --onefile flag with pyinstaller so that it bundles everything into one .exe. Note that this often causes Windows Defender to freak out sometimes. There’s nothing malicious but sometimes the nature of the portable .exe makes Windows Defender nervous as a lot of Python written malware use pyinstaller. So you’ll probably be fighting with your antivirus exceptions for a bit if that happens, but once you have your exe you should be able to link it to Steam.
> 
> If I remember tonight, I’ll build a new exe and add to the releases. My next step with this project will be integrating patching of the game’s files rather than needing to run the official launcher to get game updates.

I did use the --onefile flag but for some reason it would just instant crash whenever I ran the exe. I will have to give it another go. I can learn a lot from projects like this so I really appreciate you making it and sharing. Interested to see any future changes but love it so far!

**Comment by mike406** [comment]
That is strange that it is crashing - I can't replicate that behavior. I am using version 2.19.1 of the requests pip package. Newer versions trip up Windows Defender on my computer so I've stuck to using that one. Doing a "pip install -I requests==2.19.1" should force re-install to that version if you want to try that. I've also published a new release as well, so feel free to give that one a try.
